export default [
  ...[
    { color: "black", type: "R" },
    { color: "black", type: "N" },
    { color: "black", type: "B" },
    { color: "black", type: "Q" },
    { color: "black", type: "K" },
    { color: "black", type: "B" },
    { color: "black", type: "N" },
    { color: "black", type: "R" },
    { color: "black", type: "P" },
    { color: "black", type: "P" },
    { color: "black", type: "P" },
    { color: "black", type: "P" },
    { color: "black", type: "P" },
    { color: "black", type: "P" },
    { color: "black", type: "P" },
    { color: "black", type: "P" },
  ],
  ...Array(32).fill({ color: "", type: "" }),
  ...[
    { color: "white", type: "P" },
    { color: "white", type: "P" },
    { color: "white", type: "P" },
    { color: "white", type: "P" },
    { color: "white", type: "P" },
    { color: "white", type: "P" },
    { color: "white", type: "P" },
    { color: "white", type: "P" },
    { color: "white", type: "R" },
    { color: "white", type: "N" },
    { color: "white", type: "B" },
    { color: "white", type: "Q" },
    { color: "white", type: "K" },
    { color: "white", type: "B" },
    { color: "white", type: "N" },
    { color: "white", type: "R" },
  ],
];
